In [1]:
import torch

In [17]:
def selectmax(x, dim=0):
    sizes = torch.abs(x)
    return sizes / sizes.sum(dim=dim)

In [18]:
def softmax_1(x, dim=0):
	"""From that one dude [Evan Miller](https://www.evanmiller.org/attention-is-off-by-one.html)"""
	e_x = torch.exp(x)
	return e_x / (1 + e_x.sum(dim=dim))

In [19]:
t = torch.tensor([1.0,2.0,3.0]).to(torch.float)

In [22]:
selectmax(t)

tensor([0.1667, 0.3333, 0.5000])

In [25]:
softmax_1(t)

tensor([0.0871, 0.2369, 0.6439])

In [26]:
torch.softmax(t, dim=0)

tensor([0.0900, 0.2447, 0.6652])