In [1]:
import torch

In [14]:
def selectmax(x, dim=0):
    sizes = torch.abs(x)
    summed = sizes.sum(dim=dim)
    if summed == 0:
        return sizes
    return sizes / summed
    

In [15]:
t = torch.tensor([1.0,2.0,3.0]).to(torch.float)
t2 = torch.tensor([0.0, 0.0]).to(torch.float)

In [16]:
selectmax(t)

tensor([0.1667, 0.3333, 0.5000])

In [17]:
selectmax(t2)

tensor([0., 0.])

In [18]:
def selectmax_1(x, dim=0):
    sizes = torch.abs(x)
    return sizes / (1+sizes.sum(dim=dim))

In [19]:
selectmax_1(t)

tensor([0.1429, 0.2857, 0.4286])

In [20]:
selectmax(t)

tensor([0.1667, 0.3333, 0.5000])