In [1]:
import torch

In [3]:
def relu_max(x: torch.Tensor, dim=0):
    return torch.softmax(x.relu(), dim=dim)
    

In [5]:
t = torch.tensor([1.0,2.0,3.0]).to(torch.float)
t2 = torch.tensor([0.0, 0.0]).to(torch.float)

In [6]:
relu_max(t)

tensor([0.0900, 0.2447, 0.6652])

In [7]:
relu_max(t).sum()

tensor(1.)

In [13]:
x = torch.tensor([-20000, -12313, 123]).to(torch.float)

In [18]:
def selectmax_1(x, dim=0):
    sizes = torch.abs(x)
    return sizes / (1+sizes.sum(dim=dim))
def softmax_1(x, dim=0):
	"""From that one dude [Evan Miller](https://www.evanmiller.org/attention-is-off-by-one.html)"""
	e_x = torch.exp(x)
	return e_x / (1 + e_x.sum(dim=dim))

In [19]:
print(relu_max(x))
print(selectmax_1(x))
print(softmax_1(x))

tensor([0., 0., 1.])
tensor([0.6166, 0.3796, 0.0038])
tensor([0., 0., nan])


In [20]:
def tanh_max(x, dim=0):
	return torch.tanh(x).softmax(dim=dim)

In [21]:
tanh_max(x)

tensor([0.1065, 0.1065, 0.7870])