In [1]:
import torch

In [3]:
x = torch.tensor([10, 20, 30]).to(torch.float)
x_shifted = x+10

In [4]:
x

tensor([10., 20., 30.])

In [5]:
x_shifted

tensor([20., 30., 40.])

In [6]:
def symax(x, dim=0, eta=1):
    sizes = torch.abs(x)
    return sizes / (eta+sizes.sum(dim=dim))

def softmax_1(x, dim=0):
	"""From that one dude [Evan Miller](https://www.evanmiller.org/attention-is-off-by-one.html)"""
	e_x = torch.exp(x)
	return e_x / (1 + e_x.sum(dim=dim))

In [10]:
print(symax(x))
print(softmax_1(x))
print(torch.softmax(x, 0))

tensor([0.1639, 0.3279, 0.4918])
tensor([2.0611e-09, 4.5398e-05, 9.9995e-01])
tensor([2.0611e-09, 4.5398e-05, 9.9995e-01])


In [11]:
print(symax(x_shifted))
print(softmax_1(x_shifted))
print(torch.softmax(x_shifted, 0))

tensor([0.2198, 0.3297, 0.4396])
tensor([2.0611e-09, 4.5398e-05, 9.9995e-01])
tensor([2.0611e-09, 4.5398e-05, 9.9995e-01])
